### ISSUE TITLE
Multiple `startgame` on the same game causes exception

### ISSUE THREAD

**Issue by akowalew** [eatrunner/tank-game#4]
After second in a row call to the `http://127.0.0.1:9000/tank-game/ajax/game/startgame/?gameid=0` I'm getting
```
myapp ajax error: Traceback (most recent call last): File "/home/akowalew/workspace/tank-game/build_web/config/views.py", line 36, in ajax data = json.dumps( fun(request.GET )) File "/home/akowalew/workspace/tank-game/build_web/game/views.py", line 49, in startgame self.game_threads_[len(self.game_threads_)-1]["thread"].start() File "/usr/lib/python2.7/threading.py", line 730, in start raise RuntimeError("threads can only be started once") RuntimeError: threads can only be started once
```

**Comment by eatrunner** [comment]
Strange... I'm getting info "error":"game_is_running". Do you have newest version?

**Comment by akowalew** [comment]
Ok, you have right. My mistake. Sorry ;)
