### ISSUE TITLE
`creategame` returns exception independent from selected `map_id`

### ISSUE THREAD

**Issue by akowalew** [eatrunner/tank-game#6]
After calling this query (no matter, if `map_id` = 1 or 0 or 999):
```
http://127.0.0.1:9000/tank-game/ajax/game/creategame/?map_id=1
```

I'm getting response with message:

```
myapp ajax error: Traceback (most recent call last): File "/home/akowalew/workspace/tank-game/build_web/config/views.py", line 36, in ajax data = json.dumps( fun(request.GET )) File "/home/akowalew/workspace/tank-game/build_web/game/views.py", line 36, in creategame self.game_threads_.append({"thread":GameThread(int(params['map_id']),13), "game_id":len(self.game_threads_)}) File "/home/akowalew/workspace/tank-game/build_web/../game/GameThread.py", line 13, in __init__ Game.__init__(self, Map(mapID,mapSize)) TypeError: __init__() takes exactly 3 arguments (2 given)
```

Pulled latest version from master

**Comment by eatrunner** [comment]
Strange. On my machine function works properly.

**Comment by akowalew** [comment]
https://github.com/eatrunner/tank-game/commit/2a6efc108086712114674bd592e1f9ea87344cf0
Fixes
