### ISSUE TITLE
`moveplayer` throws an exception

### ISSUE THREAD

**Issue by akowalew** [eatrunner/tank-game#7]
After successfully call to the `creategame` and `startgame`, when I try to move player with `moveplayer` sending `http://127.0.0.1:9000/tank-game/ajax/game/moveplayer/?game_id=0&dir=up` request, 

I'm getting trace: `myapp ajax error: Traceback (most recent call last): File "/home/akowalew/workspace/tank-game/build_web/config/views.py", line 36, in ajax data = json.dumps( fun(request.GET )) File "/home/akowalew/workspace/tank-game/build_web/game/views.py", line 219, in moveplayer self.game_threads_[i]["thread"].moveTank(0, params['dir']) File "/home/akowalew/workspace/tank-game/build_web/../game/Game.py", line 70, in moveTank self.notifyTankPosition(tank) File "/home/akowalew/workspace/tank-game/build_web/../game/Game.py", line 36, in notifyTankPosition tank.id, tank.currPos, tank.faceDirection) File "/home/akowalew/workspace/tank-game/build_web/game/ServerGameObserver.py", line 21, in updateTankPosition self.tanks[_i]['pos'] = pos AttributeError: 'ServerGameObserver' object has no attribute 'tanks'`

**Comment by akowalew** [comment]
https://github.com/eatrunner/tank-game/commit/5dc06d8a5cec17f1f10383bab796d9dccf8cc334

Fixes this error.
